name: "Stremio Hellspy (private) — Filip"
slug: "stremio_hellspy"
description: "Privátní Stremio addon (Hellspy.to) běžící v Home Assistant OS"
version: "0.1.1"
url: "https://github.com/<your-user>/<your-repo>"
arch:
  - amd64
startup: services
boot: auto
ingress: false
init: false

map:
  - data:rw

ports:
  80/tcp: 18099
ports_description:
  80/tcp: "HTTP (manifest.json)"

webui: "http://[HOST]:[PORT:18099]/manifest.json"
